### ISSUE TITLE
Improve touch test

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/static-code-scan#5]
Try to find an heuristic to see if there are hover menus or not. Maybe we can look for  the most popular menu libraries.
We should also suggest the usage of aria-haspopup or any other accessibility attributes

**Comment by marknoble** [comment]
Agreed.  I've updated my site to address the other issues in the test.

The failed "touch" test doesn't really offer much in the way of direction.

I've tested my site with a variety of touch-screen devices and have added aria-haspopup="true" where CSS hover is used for a few of the menus.  In my case, tapping on the menu item that has the hover menu just takes you to a page with a more static set of menu options (not relying on hover) so the "touch" failure isn't really a failure in my case.

The rest of the site seems to work as expected with the default handling of pinching to zoom and scrolling by touch.

...so I feel that the "touch" failure is giving a bad result in my case, but I think this would be corrected if it offered more info about what elements are resulting in that false result so developers can assess impacts of addressing them on their site.

**Comment by marknoble** [comment]
>Try to find an heuristic to see if there are hover menus or not. Maybe we can look for the most popular menu libraries.

Just to help, I'm a fan of implementing hover menus by using the CSS :hover selector and setting the visibility of a DIV that contains the menu... so that'd be at least one approach to hover menus that it'd probably be wise to check.

I do use the :hover selector to change the style of elements that are not menus as well though, so it would probably be necessary to check for the use of the :hover selector in conjunction with the setting of visibility on the child menu element.

**Comment by molant** [comment]
This project is deprecated and no longer maintained. Please check [sonar](https://github.com/sonarwhal/sonar) if you need a similar tool but more flexible and modern.
